name: build-dev-communication-service
run-name: ${{ github.actor }} has pushed CommunicationService

on: [push]
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dockerCICDBram

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
          run: | echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
          env:
            REPO: '${{ github.repository }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: DockerFailures
          push: true
          tags: ${{ env.REGISTRY }}/${{ REPO_LC }}/server:${{ github.sha }}
